version: '3.8'

services:
  web:
    build: .
    container_name: scheduling_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      # Conexão com o banco centralizado
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@host.docker.internal:5432/${DB_NAME}
      # Opcional: Variáveis para o Python saber onde achar o ClamAV
      - CLAMAV_HOST=central_clamav
      - CLAMAV_PORT=3310
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app_network
      - rede_seguranca
    restart: unless-stopped
  app:
    build: .
    env_file:
      - .env

networks:
  app_network:
    driver: bridge
  rede_seguranca:
    external: true